# added turtlebot_arm/ to the name of both controllers, as suggested in https://github.com/AS4SR/general_info/wiki/ROS-MoveIt!-and-Gazebo-Integration-(WIP)
controller_manager_ns: ''
controller_list:
  - name: turtlebot_arm/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_flex_joint
      - arm_wrist_flex_joint
      - gripper_link_joint
  # - name: turtlebot_arm/gripper_controller
  #   action_ns: gripper_cmd # used to be: gripper_action
  #   type: GripperCommand
  #   default: true
  #   command_joint: gripper_joint
  #   joints:
  #     - gripper_joint
